version: '3.1'

services:
  db:
    image: mariadb:10.6
    volumes:
      - ./db_data:/var/www/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
  site:
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
    image: php-local:local
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MAILGUN_KEY: 34359ff39c727d000306f52498f69a2b-32a0fef1-6889b177
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe